### ISSUE TITLE
 Feat Req  Change canvas size please?

### ISSUE THREAD

**Issue by ShoeUnited** [T8RIN/ImageToolbox#447]
I believe the topic speaks for itself. But I'd like way too resize the images surrounding bounding box like in Photoshop, Gimp, or PhotoPea.

I would like the way to be able to resize the background canvas without having to resize the image if that's possible? 

Everything' else seems to zealously over crop on Android and I sometimes need bigger clear space around the artwork so it doesn't clip it 

Please? 🙃

Thank you for your time reading.

-Shoe

**Comment by T8RIN** [comment]
You mean something like size crop? I.e if image is bigger then strictly crop it to be exactly given dimensions, else create colored background around it (or transparent) ? That's seems to be easily done and also for the batch processing, i will try to add this later, because  I don't have much time and there are still many new tools waiting for me to get my hands on them.👀

**Comment by ShoeUnited** [comment]
I was more hoping of image is closely cropped to make it bigger around the image without  color. Something like this for example:

![🎮(1143)x(1143)_2023-09-18_18-10-33_1](https://github.com/T8RIN/ImageToolbox/assets/221434/f024fe1e-c86a-456f-acfd-4d1e60d9b0d8)

![05dd50d1-d0cf-4530-9675-cf511a80f9bb](https://github.com/T8RIN/ImageToolbox/assets/221434/07399001-7506-45c9-a523-e44955f47fac)


It's a bit of work to make stuff not zealously crop the image but sometimes I need to adjust the layers sizes without changing the dimensions of the art.

Is that doable?

**Comment by T8RIN** [comment]
I think i can do that, i will tag you here when i start, so you can tell if this is what you need :)

**Comment by T8RIN** [comment]
i think i did it :)
