### ISSUE TITLE
[Feature Request] Replace Original Image with New Image

### ISSUE THREAD

**Issue by skj-skj** [T8RIN/ImageToolbox#512]
@T8RIN thanks for making this app, all image editing needs in one app.

I have one feature request for a particular use case.
is to replace original image with new image directly in single and batch operation.

for me this will be helpful to compress fat images in jpeg format to heic and reduce storage usage.

and I think lot of people will benefits from this feature.

**Comment by T8RIN** [comment]
> @T8RIN thanks for making this app, all image editing needs in one app.
> 
> I have one feature request for a particular use case.
> is to replace original image with new image directly in single and batch operation.
> 
> for me this will be helpful to compress fat images in jpeg format to heic and reduce storage usage.
> 
> and I think lot of people will benefits from this feature.

Hello, thanks for the idea, but I was asked for a long time, but I could not implement it due to the fact that I need to delete the old file, and this can only be done if I request very high permissions, which I don't need to be in my app, but Now I'm thinking, why don't I just let the user grant all the serious permissions if he wants to use these features🐸

Another problem is that with such permissions the application may not be allowed into Google Play(
