### ISSUE TITLE
[Feature Request] Add tooltips for each image button

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#544]
![Screenshot_20231105_065414.jpg](https://github.com/T8RIN/ImageToolbox/assets/51242302/b6f41d28-a351-4788-b6cd-714942460267)

As software functions become more diverse, there will also be more and more image buttons. But sometimes images cannot convey information well to new users. Adding tooltips can solve this problem.

Design Guidelines: https://m3.material.io/components/tooltips/overview

**Comment by T8RIN** [comment]
Okey dokey, thanks :)

**Comment by T8RIN** [comment]
Added as a sheet, tooltips a too bad in compose

**Comment by codokie** [comment]
> Added as a sheet, tooltips are too bad in compose

@T8RIN Sorry for the possibly stupid question, but what is a sheet?

I could not find any way to tell what icon-only buttons do without clicking on them in the latest version.

I've read in [this tutorial](https://www.freecodecamp.org/news/how-to-use-tooltips-in-jetpack-compose) that since version 1.1.0 of Compose Material 3, there is a built in support for tooltips. So it would be great if you could revisit this option, as such a feature can be helpful even for non-blind users who are just overwhelmed by the abundance of buttons.

Otherwise it would probably make sense to add an option to display labels (content description) under any button. Up to you :)

**Comment by T8RIN** [comment]
There are content descriptions anyway, but idk how to read it properly

**Comment by codokie** [comment]
The content descriptions that you've added in 5991c19a12fd2c5fd63f4587a7303945cf19844c are only accessible to those who use a screen reader (such as TalkBack).

Sadly I can't think of a better way to implement tooltips other than by creating a composable function which returns an Icon wrapped in a TooltipBox. This would involve replacing all instances of Icon with the new function.

It does not seem like there is a way to read the `contentDescription` of an Icon in Jetpack Compose..

**Comment by T8RIN** [comment]
Yup, no way 👀 so this will be never added, i have no time for doing that, also in my opinion tooltips are useful only in specific places, so i add them only if necessary
