### ISSUE TITLE
Improve the user experience 

### ISSUE THREAD

**Issue by pwd-github** [T8RIN/ImageToolbox#569]
First things first, I would like to congratulate you on making such an excellent app.

However, I think there's some needless complexity that makes things seem far more confusing than need be.

1. The settings at right sided drawer. It's confusing and makes the app feel daunting an intimidating. It would be far bettter to have Settings as a full page and each of the sections as their own pages.

2. Reduce the superflous use of cards, particularly the elevated cards. In fact the way they're currently implemented, lists would probably be a better implementation. However if you make the icons bigger, and have two per row in the style you've formatted the card on the picker screen, you can create a 2*X grid on the main three pages.

3. On the picker screen, you don't need a FAB and the card. 

4. The edit screen is a daunting and heirarchial mess. Why is the file size the title instead of the filename? And why are there so many cards that could and should be grouped behind different navigation bar options? The "most important" options are sitting there without any title or tooltip too. Literally have at the bottom of the screen in a navigation bar, Crop, Filters, Draw, Erase Background, Edit Exif, Export Options.

5. Why are there no tooltips?

**Comment by T8RIN** [comment]
1. I like side settings, because each group has not many items, and screen for each would be too much i think
2. You can disable shadows in settings, or switch to bordered ui there (didn't get about the grid)
3. I like it, but maybe i'll provide an option to disable it, just more ways to fill empty space and ensure that if you tap somewhere image picker will be opened then
4. Because I can't even get the filename using photopicker sheet,  and also it's good to know how much your operations will compress the original image
5. because In view system they were automatically provided, i'm writing on compose, and each one needed to be implemented by me, i likely add some info by sheets, how it's done somewhere
