### ISSUE TITLE
Feature Request: A Novel Image Encryption Scheme Based on Collatz Conjecture

### ISSUE THREAD

**Issue by Pantyhose-X** [T8RIN/ImageToolbox#597]
> The Collatz conjecture is an unsolved problem in mathematics , which is named after the mathematician Lothar Collatz, who introduced the idea in 1937. First part of this paper, we have approached the Collatz conjecture in a constructive way. In the constructed structure, every Collatz sequence converges upwards and we have defined a function g for any odd number, which diverges downward through the structure. For every term in the divergent sequence generated from the function g, we have a convergent sequence generated from the Collatz function. We have showed the function g is divergent for any positive odd integer. Thus, our present study provides a good justification for why the Collatz conjecture holds true for all positive integers. In the second part of this paper, we have proposed a new symmetric cryptosystem in which the sender and the receiver hold the secret key pair (k, l) which has been chosen randomly. A plaintext is encrypted using a large, odd number k, and l number of iterations in the Collatz sequence starting with k. The Collatz sequence is a chaos-based sequence and for every positive integer there is a unique mapping, and a slight change of the number makes a huge difference in the generated sequence. Thus, the chaotic nature makes this cryptosystem more secure. This cryptosystem has uncomplicated transformations which are very simple to be analyzed and is efficient because the only operations involved are multiplication and addition. It can be used to build more secure cryptosystems by repeating the encryption process or implementing it with other cryptosystems.

### collection of papers
[A Novel Image Encryption Scheme Based on Collatz Conjecture](https://www.mdpi.com/1099-4300/20/12/901)

[Novel Cryptographic Scheme based on the Collatz conjecture](https://www.researchgate.net/publication/367271522_A_Novel_Cryptographic_Scheme_based_on_the_Collatz_Conjecture)

[Encrypted audio dataset based on the Collatz conjecture](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6811906/)

https://en.wikipedia.org/wiki/Collatz_conjecture

**Comment by T8RIN** [comment]
I read that you send but I didn't get how to encrypt image and then decrypt it because there is only math expressions by the way I'm asked to charge upd and he said me that

The Collatz conjecture is not a suitable method for encrypting and decrypting bitmap images. Encryption typically involves more sophisticated algorithms designed for secure and reversible transformations.

For image encryption in Android using Kotlin, you might want to explore established encryption algorithms like AES (Advanced Encryption Standard) or other cryptographic techniques. Keep in mind that handling encryption requires careful consideration of security principles and best practices.

If you're interested in a specific example or code snippet for image encryption using a standard algorithm, feel free to ask!
