### ISSUE TITLE
Real time filter changes

### ISSUE THREAD

**Issue by NikunjKhangwal** [T8RIN/ImageToolbox#941]
This is probably one of the best qol addition this app  can get. Having the filter value change in real time gives a much better idea instead of changing slider and waiting a bit. It makes editing so much faster as well.

https://github.com/T8RIN/ImageToolbox/assets/99175083/a0f6ef52-045e-4a47-8b85-2e50f1122cb0

**Comment by T8RIN** [comment]
My filters can be complex, so it's impossible to overcome delay

**Comment by NikunjKhangwal** [comment]
Is it possible to implement hardware acceleration by any way?

**Comment by T8RIN** [comment]
They already have that|👀

**Comment by NikunjKhangwal** [comment]
I see. Well fair point, closing the issue.

**Comment by leleogere** [comment]
I know that this issue has been closed, but I still have two points to raise:

> My filters can be complex, so it's impossible to overcome delay

I get that some filters can be complex, and not applicable in real time. However, some of them are not (like saturation, contrast, however how would other apps be able to render them in real time?). Wouldn't it be possible to have an internal flag on those "simple" filters, that would render them in real time when modifying the slider? And have the "heavy" filters be applied only when the slider is stopped?

The second point is that I try to modify a 2.8 MB file, and it takes quite a bit of time between each update of the slider (~ 2s between the moment I release the contrast slider to the moment the image is re-rendered), so it's quite difficult to precisely find a suited value. However, when working with a compressed 250 KB version of this same image (50% resizing + JPG 80%), the processing is quite faster (< 1s for this same task, which is still a lot, but it's better). Which makes me believe that the rendering happens on the original image, right? Wouldn't it be possible to work on a small preview of the image so that the processing is faster, and only apply the filters to the original image at export time (or eventually if the user want's to zoom in)?

**Comment by NikunjKhangwal** [comment]
+1, solid ideas

**Comment by T8RIN** [comment]
That's not done, because other apps have only simple filters and they are all done on the GPU surface directly, now part of the filters are GPU, part CPU, and to make chains work correctly each filter applied by cpu on bitmap, even if some filters do it for me quickly because they interact with the GPU, result of this fast calculations are copied from internal glSurface to native image, so if i had only GPU filters, and have no ability to chain large amounts of them, of course they will be fast, but i have no such ability unfortunately

**Comment by T8RIN** [comment]
Idea pf my filters is not to be like in other apps, this is the first app that i have seen, that van apply nearest almost all filters, to unlimited amount of images, with unlimited chain inside, with same configuration to different images successively, this brings ability to make photo correction on 100 photos with same config, also you can create templates, and use them as separate filter, also share it via qr code like it's telegram account

**Comment by T8RIN** [comment]
Mostly all features in mine implementation is done Consistent with what is on the market, as I create a completely new way of interacting, since it seems very convenient to me, unlike all these identical photo editors, Of course, despite this, I would add a display of filters, if not for the technical limitations due to the fact that I can quickly show only one filter at a time, and I may have 10, 20 and more in one chain

**Comment by leleogere** [comment]
I get that there are technical limitations, however I'm still not sure how Adobe's Lightroom and Google's Snapseed apps manage to display real time modifications on the image. In both those apps, you can apply filters in succession, access the stack of filters applied, modify them, delete them (not in a sequential order, you can get back to previous filters to modify them). You can also create templates/styles that you can apply to other images. Snapseed also allows sharing a filter stack via QR code. The only difference is the batch correction, which is not really easy as afaik you need to open each image, paste the filters stack onto it, and then export, but it's merely an implementation detail as the copy/paste filters stack logic is present.

Is that because, as you said, all the filters they propose are GPU? What kind of filters are CPU?

Sorry for those questions, I'm not saying you are wrong, I'm genuinely trying to understand! :)
